Develop
joeyliao127/Weather-Dashborad pull request #3
Opened 2023-10-17 08:56 UTC by Melodystart

2023-10-17 09:03 UTC, joeyliao127 requested changes
將fetch部份程式碼包在async function，方便Katlyn調用資料，Thanks!

2023-10-17 11:51 UTC, Melodystart commented
此版將原程式碼分成兩個函式，fetchAPI()抓API，countryData(country)回傳特定country資料

2023-10-17 13:53 UTC, joeyliao127 requested changes
需微調程式碼結構，改用async Fn

2023-10-17 14:14 UTC, Melodystart commented
已調整程式碼結構，改用async Fn，thanks~

2023-10-18 00:31 UTC, joeyliao127 reviewed
ok, good.

2023-10-18 00:32 UTC, merged